# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "3.1.3";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };

  "artifacts" = {
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-javadoc.jar";
      sha256 = "C570B6A2714A88AE3B77E88FF6C608B9EA516AC8B739EBF4B205D67D07CCFC28";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1-sources.jar";
      sha256 = "E7D07607CF333D0412C97D60BC956627B0966FFD304F2323EE3ABA0D6D6C96DE";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar";
      sha256 = "203CEFDFA6C81E6AA84E11F292F29CA97344A3C3BC0293ABEA065CD837592873";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom";
      sha256 = "3E0C5721FB26BE732CCDF13DB1C59DFEEE0A6DB269EBCC7507EAD1C763A6108B";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-javadoc.jar";
      sha256 = "F10E6253A03E199040A3C54A60BE2899BD61D43D01D49D8DDB4D6D04EE6C1065";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1-sources.jar";
      sha256 = "C985C212836804F22BF69AA8A4D8838DD74AC9FE5A3513120DB4DDFD04574B2E";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar";
      sha256 = "CC899CB6EAE0C80B87D590EEA86528797369CC4FEB7B79463207D6BB18F0C257";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom";
      sha256 = "4D09B42B2ADCFE5CA73F541E42D1E36A8BF483594DF09C43BA8D31EB67E04626";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-javadoc.jar";
      sha256 = "3F56F12A787743E93D1E1B57691DAE196DCEC142D47AE7A6256CCA47923F592A";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1-sources.jar";
      sha256 = "C1EDCE07C4C71FD9E3636442457F43DF6A810B26F567638C0EF575B08B91D704";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar";
      sha256 = "F2CA3C28EBDED59C98447D51AFE945323DF961540AF66A063C015597AF936AA0";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom";
      sha256 = "98926399D5072408C20CD63063FBE29CF0923FC5061A3A56D6987F4DFF6FA223";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1-javadoc.jar";
      sha256 = "63EF8B41F40C8079AE5B92441F2C2D4C927D75B8920A364995C9A2D221D2EDAF";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1-sources.jar";
      sha256 = "6ACE28B8079E68B78CD89ACB0806F2162A553DA7AF0FB7136A3E00C9F0B71FE2";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1.jar";
      sha256 = "58C9DB6C379A7AB0BD4F5722A0695B812FDD698D073A8AAA24FAE74D3B802F7A";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.1/jackson-dataformat-yaml-2.12.1.pom";
      sha256 = "48ED20FA7B29E35A2C5C1CB3A83F6D6CF55BA98DEAE4117A1FC2ADE349F65259";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.12.1/jackson-dataformats-text-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.12.1/jackson-dataformats-text-2.12.1.pom";
      sha256 = "3099140329E99025E087FF98C4F005F327CF15DA37C3FFD67F63B8CF5207B15C";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-javadoc.jar";
      sha256 = "18E0CE4BA689DCEAF9353E8D0C8CC7C845569BACB306DB91ABDA5F383E68D58A";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar";
      sha256 = "B99AE335E94822194AB14DE4DBEE6D6FA75393A1C6788B13A3EAB167E40177A9";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar";
      sha256 = "B1B34405C980766CCE6C283FDC5039A274EA3B911F097B6807C21E1213B10292";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom";
      sha256 = "F44E4DA4876BB633CEBDB48D15F3D7D6D4F8B3D7DC5AFDBCD4343142B6C5C631";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom";
      sha256 = "93A8C78755A31977508021DBB3883C0DD740A06BB1C67FF4942E096C132419F5";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom";
      sha256 = "083B20A4231BB0516D6E1A08248C9FBCE473583A122A07FD2E0EADEFF6908A38";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom";
      sha256 = "62AA1C1679ADE09F173DBF1B6C32D35C55E75800238FD5E48F13AA4337C0875B";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom";
      sha256 = "C67B1D8ADBD06EFCDAC8EEF9EF569787F236E3869B81F86FFFF205EE1B4CB467";
    };
    "nix-public/com/fasterxml/oss-parent/41/oss-parent-41.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom";
      sha256 = "AF650FA4DD400BC5769320BCEF08ED93813F349CABE8213D469ACAFBBD945D8A";
    };
    "nix-public/com/google/protobuf/protobuf-bom/3.7.0/protobuf-bom-3.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-bom/3.7.0/protobuf-bom-3.7.0.pom";
      sha256 = "A36A2C2C54C242558B05C6003875FD810B270EF573E5903302E1A27890C31196";
    };
    "nix-public/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0-javadoc.jar";
      sha256 = "1BF4487B7C8645756A8C772BAFD79D2DD7D83F50FA491197F44BFE050B6998BE";
    };
    "nix-public/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0-sources.jar";
      sha256 = "116ADC64F2E67A9F2961C410B1FBE029447C4B39C62F6AE93797989E38C85B83";
    };
    "nix-public/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.jar";
      sha256 = "DC7F93E3A3DC2C11BE5BA9672AF3E26410F0A3289312DBF2260D4D8A0C711A51";
    };
    "nix-public/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.0/protobuf-java-3.7.0.pom";
      sha256 = "2EB5D5F9663069BE2BBECD07836C67BBCFE4DD6B951D022F6F58DA361C005E3B";
    };
    "nix-public/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-parent/3.7.0/protobuf-parent-3.7.0.pom";
      sha256 = "912A56FF543E6990CC908E75B3E14EBC675E57D2A558D23C3F068001F2E5702C";
    };
    "nix-public/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10-javadoc.jar";
      sha256 = "0ED7AC01733DB0D240D9C4EEBB12A6DEE0B914133C59DF2887D0C0FCE995BEA8";
    };
    "nix-public/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10-sources.jar";
      sha256 = "230E3AD87455354A12FF662EC1488491B087ABA7F2D738716EB03A62E836E0D7";
    };
    "nix-public/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10.jar";
      sha256 = "9562BABDA9D02AB88A55068C30DD6F35A5A401DDFAFB19B1A9CE0092AF67027C";
    };
    "nix-public/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/utest_3/0.7.10/utest_3-0.7.10.pom";
      sha256 = "69ACFA73E2CA6A80C91B4E7835135EA6EA1223C317626E0A1D6415D9987AAD9A";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12-javadoc.jar";
      sha256 = "9ECBF658CB2B0EA3518714005EA8D6C21765634E2938622244A1471CAF1F1168";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12-sources.jar";
      sha256 = "1B2849B533CC37C613EC25EADE63CC25D4C6CB19DE291D09B6496ACCE17D6768";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12.jar";
      sha256 = "F808CEFD4B7EA9009023CF1C0C466A82EC3C0FCA934D42791E2AAF18ADEB2BBA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.42.12/flexmark-ext-anchorlink-0.42.12.pom";
      sha256 = "69F5AC01AD0B08AC4EF10C5F5BCE23CA34C44B61C5CEBA9CB76F74841D00636D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12-javadoc.jar";
      sha256 = "F097DE4389EB591860ABBBD8FA2D5A36C3F78E4D49CD4F9C06C7EEEBBA09C00D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12-sources.jar";
      sha256 = "954531EBAC5D22093CFE3283A3308CD631F75C925843F2A2D35EAEEEADEC0E12";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12.jar";
      sha256 = "74E560037C32C2D01107E64190FF75529F22FC5BA87C4BBBA435E02400A4E63D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.42.12/flexmark-ext-autolink-0.42.12.pom";
      sha256 = "3D3C87E2EC5F59890E69F3143287B863E94E64B66FACFC094B252255C567B927";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12-javadoc.jar";
      sha256 = "A6065AC3C4C0CE3F026D0D7B48227A88333288707F56D79AB93DBFA7805D7625";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12-sources.jar";
      sha256 = "FD81B33BD62F2F3F881279FF8BD4A61549DAA6723C71D09EE943962A7F2E3414";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12.jar";
      sha256 = "45F8B0FAD2AE77F16D24E8F93260405635C9B085F388ECB9B870AC19FF54FF5E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.42.12/flexmark-ext-emoji-0.42.12.pom";
      sha256 = "6A1459FE9C0CBD079E7FB8CC14EF3BFBBEF35A42C9A2A45B6066CB61DBD1C078";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12-javadoc.jar";
      sha256 = "2E1FA28DC6A03C65FE164B7CDB8A31FB5487C1C363263567EA3E35A867130A84";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12-sources.jar";
      sha256 = "6045F41444B7EA276926EB63834C064321F298A4E263A0E5D3C06359E10F28C2";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12.jar";
      sha256 = "13BF5D2848D8905DF9BA8361E61AF871B03C10185933588DC0B16FFA66F33B9D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.42.12/flexmark-ext-gfm-strikethrough-0.42.12.pom";
      sha256 = "224304554C25F57DA10053FB9D5FE5CBC970E6A6874EA133A8054E5DB2338311";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12-javadoc.jar";
      sha256 = "23C60C2F360651FBE63577496D507D79316AD2D6905B213C2B23111CA006271A";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12-sources.jar";
      sha256 = "9184869E3A5E36D6E222642B8F725A426EBD50236CC917BB8B1B92D4BD00E937";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12.jar";
      sha256 = "314F63ACFC95E4EB56D7E4AB1F75505912DDD0664D97953A281A7E78BB4DEB53";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tables/0.42.12/flexmark-ext-gfm-tables-0.42.12.pom";
      sha256 = "215832CF08EFB7E2149603416B4F188FCAE4EBEC8224CC08637E8BC63982B96E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12-javadoc.jar";
      sha256 = "4D1C46F557620E1DCBD8DEDE0F20888D6B964E5D282087159E8840CF08616AC4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12-sources.jar";
      sha256 = "0D54209BDAE933E4CEB41AAE2598EC1818E35139281A7F9990F485A6E343C1DD";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12.jar";
      sha256 = "587DD5E9C6DFACB458EE305E17D0F2A0881BC78CE08650C05921A0DAFF88928C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.42.12/flexmark-ext-gfm-tasklist-0.42.12.pom";
      sha256 = "A148D39107BA2203B7D74E47E878A1E467434269C370AC251D5C25884BFC4C14";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12-javadoc.jar";
      sha256 = "CA0CE10CA08785B8C81A177200F5F4FBA0E7287C6CA6A9B1FD6B941449FD77E4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12-sources.jar";
      sha256 = "5315C2D6EDF88812B3823B3EE9DA2201F438502820CEC68C9CA0FD369B85D0C6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12.jar";
      sha256 = "FA2FF6CC9507C9C4DC157BA31EF5CB8A5E055E2FC865CD1F4B101A6D78A5CB00";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.42.12/flexmark-ext-ins-0.42.12.pom";
      sha256 = "A632A11EF1267D5B4AC0986230B366B280DC3C5FEE90D944F26D54DC9DD93700";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12-javadoc.jar";
      sha256 = "D41DA51AB004148501DCDEBC3685C1D8A7FA5AC0AE3F8AB5336E831B241D8977";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12-sources.jar";
      sha256 = "E769D491C9904ABAD69E6F25C569E717EC12E8DF54FAAF06B516A22D3BC22223";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12.jar";
      sha256 = "73F7CC74B83EAE916F1B4A192414FD8E31237C01647AC087C3163F560714270D";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.42.12/flexmark-ext-superscript-0.42.12.pom";
      sha256 = "0F9FEBC202449C0AA536303FA844F3F21AEB9BA994A9316F6F7013FFA543B56E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12-javadoc.jar";
      sha256 = "DF17068C69444645253DB8C7D91F70BDE26690FFF3BAC197EAA3612F35633109";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12-sources.jar";
      sha256 = "C76D0122023E7DDEAAA6C762B94FF0C9E2A140124E5270D811B8B1DE6FD37CD4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12.jar";
      sha256 = "24787209A24AE0AC32897E9A575AFE9F6E4175319F08EF23EBB0CE4B8467706B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.42.12/flexmark-ext-tables-0.42.12.pom";
      sha256 = "86EDCC91880D4D51CD516ADC3866CEE9749349BD6940CBFC0A8884D3FD31D678";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12-javadoc.jar";
      sha256 = "CE1D4BC749EDA7E5967F2FE6655EC098F9B34606F5119F41AA0DCDC25268149B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12-sources.jar";
      sha256 = "95E96D9D58B28014B890C2F1C3FCDAA083A1B6A9E2CB2B51EA601F42B261DB8E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12.jar";
      sha256 = "C92FFF460EFCCD202AB87A90B13352FFA3D6AEF07BA9B926F6629A16612C0CD4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.42.12/flexmark-ext-wikilink-0.42.12.pom";
      sha256 = "0CB292DAAD64DDAE7425B6E9A04B9A917C32B4789B29D4B48E10F19BF722EDBC";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12-javadoc.jar";
      sha256 = "916CCAA55134C34865B4D8FB5946654E00480FA1F96704FCB65CC6FF3B265093";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12-sources.jar";
      sha256 = "D9E906FE48476FD8851B0CEB6643C406379A30802013CEE212CBFD4F03D04507";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12.jar";
      sha256 = "4D4402AA19E9B27266FDDE925B90E8DF6DE82C809B9157584FB73080A0092E5F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.42.12/flexmark-ext-yaml-front-matter-0.42.12.pom";
      sha256 = "C1FA269E9171117222EAED9807F22AE941289CF1C980DE1C02E30314EC3A2184";
    };
    "nix-public/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12-javadoc.jar";
      sha256 = "1A1C896DF82B69798FEC1B435EE5C8130481E8C234E40B669FF50602ED1AAD7B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12-sources.jar";
      sha256 = "4B2E8F5DBF00BB253C10FDDB98C313A86331C8EA28002151267B983C7CE5491C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12.jar";
      sha256 = "B47F6765693648820A56B2042FF732F9D45A07312B80EB8FCE176C091B3226C8";
    };
    "nix-public/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-formatter/0.42.12/flexmark-formatter-0.42.12.pom";
      sha256 = "4C7D2CDD4468E8B82CE3696F6DD75A5278E0194DE927459F1CA8A4181EF445AF";
    };
    "nix-public/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12-javadoc.jar";
      sha256 = "39E967A9CA9DC00B95AD3521C3A7B5EFF1EAA9425D7B905242688CB60D177ED7";
    };
    "nix-public/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12-sources.jar";
      sha256 = "3EABED01A15633D8839567ED77D225144CFCD6C8C77F6B60057CAC274E6F1AAD";
    };
    "nix-public/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12.jar";
      sha256 = "6D7C4ED535624C38F8DF9965B2825F1605490A79FC8861FFC441B9C9631F31A1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-html-parser/0.42.12/flexmark-html-parser-0.42.12.pom";
      sha256 = "854AA3F65B49766A41E07D189A3B0017ACDDDD53C0C96A2CAD4399696CD1BD95";
    };
    "nix-public/com/vladsch/flexmark/flexmark-java/0.42.12/flexmark-java-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.42.12/flexmark-java-0.42.12.pom";
      sha256 = "C2252C264BD5F2900C921AE7AF065D031F6C30FC351A5EFCEC79F66D816C1E6C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12-javadoc.jar";
      sha256 = "4A45AECB23324D3F744BAD8935F24CEE3918DA24115ACFDA72F56A0B123418BF";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12-sources.jar";
      sha256 = "1E399D93ED84D5364C59613DACC2B6E75DBADDC3F9053E6FB26C3E6AE92DBAC0";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12.jar";
      sha256 = "EA17E478AF63BB088304584755B4D281C9D72DC0DADD4FC8B3BF6DD266EBC5D3";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.42.12/flexmark-jira-converter-0.42.12.pom";
      sha256 = "B8F295872222D10E6BB5DDEC8EA5D3A4BBD1EB8360669DFAA692A9ACD87DAA9A";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12-javadoc.jar";
      sha256 = "4840058CD0B51007A1725FFAE9669F335DA2A50C542032C553FA3E06A8040879";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12-sources.jar";
      sha256 = "F0D907D80FF131481DF3CFA3BC5422DA60214BBCDA8A340FEF340B37DAD1BDCE";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12.jar";
      sha256 = "5B7C2ECF4AD503F4E45D17F599C2AD6C60B4997A7AA54DCF4FA85521B0EAE0C8";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.42.12/flexmark-util-0.42.12.pom";
      sha256 = "830F0B4D47E29A3EA76081559B511104FEA93B869E49F6ED303D37462D6DD3EE";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12-javadoc.jar";
      sha256 = "6C4CEA2A3BA4CB45FEA8CFF137086578D6628DDFD6BCA73CD3D83C250BF398D1";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12-sources.jar";
      sha256 = "AEC1FC81EEC108FF7AAD237FEC85C621706964BA6EE3EBD2EA58D583CB474B67";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12.jar";
      sha256 = "2EAB20000AA29504D8342D34A7C33DCB925CB2ACDB365879AE5D1659B5F0A664";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.42.12/flexmark-0.42.12.pom";
      sha256 = "B10053A364AC48B611D75EC8652B62B4BF9AD8B3140E08A190BCC192EABB4850";
    };
    "nix-public/net/java/dev/jna/jna/5.3.1/jna-5.3.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1-javadoc.jar";
      sha256 = "D1EB612DAC72D1C4CCFBFA9CE8ED12F862DAB745D4A0DEAD9A37746062522F84";
    };
    "nix-public/net/java/dev/jna/jna/5.3.1/jna-5.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1-sources.jar";
      sha256 = "B2C47BFE2B471C3E03E0E7FFCA9C2D23C3E6F63FCA8A443A00129C957235AC5C";
    };
    "nix-public/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar";
      sha256 = "01CB505C0698D0F7ACF3524C7E73ACB7DC424A5BAE5E9C86CE44075AB32BC4EE";
    };
    "nix-public/net/java/dev/jna/jna/5.3.1/jna-5.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.pom";
      sha256 = "B0B22C3EE3AC92F83A24EE21267248BA3439327E315CAC29E4C01FEA24E0E487";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2-javadoc.jar";
      sha256 = "528F471362AECA484B98191344EDCA12816455987C4C0E0DDF6B58F20B7F5DC8";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar";
      sha256 = "C3D1225F1ED152B979E9D43C76B8421ABBC7FBC424D1B57286C3040E8EDE59AC";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar";
      sha256 = "A948C26558E31FB445B5F1A2561C4518136A5D74046E4AB12BFB6010F6B0CC5B";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom";
      sha256 = "846DA39098C20BE8631523C62928E4DD2B4CF7686D428678AAE50060EEF009B8";
    };
    "nix-public/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom";
      sha256 = "BA99CB25D2390F38680C7502842A0EE0959D1E6403E013CCFF698FD5856EEAD1";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-javadoc.jar";
      sha256 = "9EC39228BAEECF6FA47493D1C7FBECAE082D53DC474548DED27AB4C36DE2093D";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar";
      sha256 = "6290B44CC5ABAAE2D747C966704E80CDFD742B4E2E0C8F9597F84A550E0D7F47";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar";
      sha256 = "4C518B87D4BDFF8B44CD8CBC1AF816E944B62A3FE5B80B781501CF1F4759BBC4";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom";
      sha256 = "DC09CBA98C25D3C06E4AEC516885D4C3AF03062BA55F4FE6283FC9CF176A60FB";
    };
    "nix-public/org/apache/apache/23/apache-23.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/23/apache-23.pom";
      sha256 = "BC10624E0623F36577FAC5639CA2936D3240ED152FB6D8D533AB4D270543491C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-javadoc.jar";
      sha256 = "46DB7CE216FA68D4E5CCFEE233502CE85BAA128B7EA8A0E9DFF7A4A8008957BF";
    };
    "nix-public/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-sources.jar";
      sha256 = "325A4551EEE7D99F7616AA05B00EE3CA9D0CDC8FACE1B252A9864F2D945C58B3";
    };
    "nix-public/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0-tests.jar";
      sha256 = "B98C155ACACBF5A17459453E28BBE572EC097455671AA684D1C880DA07BAE6ED";
    };
    "nix-public/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar";
      sha256 = "D919D904486C037F8D193412DA0C92E22A9FA24230B9D67A57855C5C31C7E94E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.pom";
      sha256 = "82D31F1DCC4583EFFD744E979165B16DA64BF86BCA623FC5D1B03ED94F45C85A";
    };
    "nix-public/org/apache/commons/commons-parent/52/commons-parent-52.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/52/commons-parent-52.pom";
      sha256 = "75DBE8F34E98E4C3FF42DAAE4A2F9EB4CBCD3B5F1047D54460ACE906DBB4502E";
    };
    "nix-public/org/jline/jline-parent/3.19.0/jline-parent-3.19.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.19.0/jline-parent-3.19.0.pom";
      sha256 = "DC2807225359ADFFD593C60A7D1352969554113A0A5A20962F23A1CFD6539FFC";
    };
    "nix-public/org/jline/jline-reader/3.19.0/jline-reader-3.19.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0-javadoc.jar";
      sha256 = "A100FCAF3C81B39B8AAB67445C363A2BB82ED3D1A0309D07747B6EA81499E4C0";
    };
    "nix-public/org/jline/jline-reader/3.19.0/jline-reader-3.19.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0-sources.jar";
      sha256 = "74EAB73D50E5E23C649CD0EA149121F4F33424A6B2497756E2C2F08B363CF5D3";
    };
    "nix-public/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.jar";
      sha256 = "5A794C15884538C312A37C1B49CF025A013D8303AD31EADB53D4F8AE091EF355";
    };
    "nix-public/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.19.0/jline-reader-3.19.0.pom";
      sha256 = "17A6F41CF7D425BBA7A5E9FE09CEDC284618DFC3E019A24A481FD266BD5F5E18";
    };
    "nix-public/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0-javadoc.jar";
      sha256 = "C013266FBCE22AD9F24A4D091F8782368307D6463EF1CD120537335707344E46";
    };
    "nix-public/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0-sources.jar";
      sha256 = "8BB10C163466591935B8ACCDF3B1793CC83478A56FA2A767F11810F110C2DE30";
    };
    "nix-public/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.jar";
      sha256 = "4A86975BA94756EAF70DEA642D8D4C32535B65479050B56C476DC8C6B0519331";
    };
    "nix-public/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jna/3.19.0/jline-terminal-jna-3.19.0.pom";
      sha256 = "917B862A28EFFE6D8A3C4C1132FFEDB71045833ED83DBBC4C724528D52AEB857";
    };
    "nix-public/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0-javadoc.jar";
      sha256 = "47A5408E9EDCC4567FC37EF19798FDF23A6FC8D14B42912A4899A2D39CEFEA95";
    };
    "nix-public/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0-sources.jar";
      sha256 = "249E29E67E300D978491FCFBDBCED5C9ECABEC8AEAAF36145EDFD5E890F34AC6";
    };
    "nix-public/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.jar";
      sha256 = "ABDBEAFA38C4CCD82578C1F3D08EA48AF439EFF194D23AA3BAE18FBE93B4DCF0";
    };
    "nix-public/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.19.0/jline-terminal-3.19.0.pom";
      sha256 = "DB5F50D0615EB423BF46AEF97BF0E2FFCF96F135FFF6028FB6F8FFA6DF280B98";
    };
    "nix-public/org/jsoup/jsoup/1.10.2/jsoup-1.10.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2-javadoc.jar";
      sha256 = "18E35F748FE0119DA9BBC5CD9F8615F7EB33022FD49B996CD23787746480935E";
    };
    "nix-public/org/jsoup/jsoup/1.10.2/jsoup-1.10.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2-sources.jar";
      sha256 = "B521E023240AD0D9F6B7D6B6D51892C4E481630DA15E359C7EB632A72FC12C97";
    };
    "nix-public/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.jar";
      sha256 = "6EBE6ABD7775C10A49407AE22DB45C840CD2CDAF715866A5B0B5AF70941C3F4A";
    };
    "nix-public/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.10.2/jsoup-1.10.2.pom";
      sha256 = "01A3888FEBAAFEDDFC9CE65CA696554A013ABF927BFB555A502F367A6D7EC113";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-javadoc.jar";
      sha256 = "BDBD84A9CD843B17CE2887F6A1CD973C692772E381B870F8792A77631D733A6A";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2-sources.jar";
      sha256 = "C4A9E9AA27494649AA0C73289F4AE00B6F83BDDBF0050349B390D0E67BFA7581";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.jar";
      sha256 = "A601BA7CE2E2C6E744D4EAC793A76707C0121576170EF717EF7A81F2343ADA1A";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom";
      sha256 = "DEF87047A7F3BA4817B256AC9361725865104DBE8AA5CC967068313B136D431A";
    };
    "nix-public/org/jsoup/jsoup/1.14.3/jsoup-1.14.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3-javadoc.jar";
      sha256 = "4A476A8C863F55E0DCBA22E36AA41ADE0312DE80F244B5E992B0DE028277E6A0";
    };
    "nix-public/org/jsoup/jsoup/1.14.3/jsoup-1.14.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3-sources.jar";
      sha256 = "8A8120654188CCB1A10CA7B84D2BE13340CB7500743B257896193C192A2ED8E3";
    };
    "nix-public/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.jar";
      sha256 = "92AF19EC57CC77637DB4490F0F5011F0444D353209CE36083BAC428F9B81A39C";
    };
    "nix-public/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.pom";
      sha256 = "52C5BCEA815708A396AACEB14199B96798FC3219AD05236F01A2ADB4C85E9061";
    };
    "nix-public/org/junit/junit-bom/5.7.1/junit-bom-5.7.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.7.1/junit-bom-5.7.1.pom";
      sha256 = "0B9B14A3D62106FAFE8C68A717B87B87AD18685899451B753C04FA41B6857784";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-javadoc.jar";
      sha256 = "57C8C2132370DFC455FE19D67E2958A3C75A2634CF97D9B4166B110C65A6391D";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar";
      sha256 = "26D6FBA888C9E332F6357773EF0500A7552C2453779A7D3E5D163E079546D8A8";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar";
      sha256 = "A80BE030F6386F18111CAD9161C0B6983157352A1B59A59E6002172F0D321C04";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom";
      sha256 = "916755647A34CCB367E11834D28380198C834ADFCF660E0D983E375B8F5C28F2";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1-javadoc.jar";
      sha256 = "B0EE590293E74384B1ABAEEAB5D7A87E544069BDAC035BA31582FA461CD3381A";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1-sources.jar";
      sha256 = "990A242B482418D7D4B85F4257106768DC3540405CB921BF54AE29F20E686DD5";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1.jar";
      sha256 = "8C34D8F56614901A1F3367B15B38ADC8B13107FFD8E141E004F9DE1E23DB8EA4";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.2.0-scala-1/scala-asm-9.2.0-scala-1.pom";
      sha256 = "E61E90128C910F452FBEBA1CB6DC5EEA9A06DEAD02969DC8A68504E230EC6F4C";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-javadoc.jar";
      sha256 = "A067CF9DE859FD1E6DD56541F95431E4C37D71BFE5E9EEF2E5276DD05FF8B2FD";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5-sources.jar";
      sha256 = "D7B00DEDCA0CC7AE11FA32CAE24D4059301164B0699C01940B0F21FDF69676C3";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar";
      sha256 = "52AAFEEF8E0D104433329B1BC31463D1B4A9E2B8F24F85432C8CFAED9FAD2587";
    };
    "nix-public/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.pom";
      sha256 = "8A83D05DC350A4DD7396BBB632EEBA46833A852B79893DC8946BBC33C614D4E2";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar";
      sha256 = "5D6362FFC5A4DC73E4AA839636A226E56EE371C1658480A307C8104CAF3CC9B2";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar";
      sha256 = "FCFBDB5FA409A10C0B0AF775382D19CD648663E325A6CD5212F0FED00AF31824";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar";
      sha256 = "A0882B82514190C2BAC7D1A459872A75F005FC0F3E88B2BC0390367146E35DB7";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom";
      sha256 = "4AE70B3CB0C215D69AEAC28C9212E6811F9EB978956782340608933420880D52";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3-javadoc.jar";
      sha256 = "1453DF2621BCC589BB22C48E8C2ECA6F526D60016B1C6DE3329C971E093997FD";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3-sources.jar";
      sha256 = "ED413714F27A52F2535298A74824EAB8D6D99B32CED1A12730BA7A154C351F64";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3.jar";
      sha256 = "140C7BC825B9DF3CB69A093ADC4F11F7F0992F1FA87BAE10D16E89020FE03E82";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3/scala3-compiler_3-3.1.3.pom";
      sha256 = "A322F95BF7D038957E1F916FF6F59A9F0A10729FC7662FE0398C1D4FB05B96F9";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3-sources.jar";
      sha256 = "5101D6C425EA373E76F7DEF352A124D41C51F4EBEAAAA8F861E7F13E6B028275";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3.jar";
      sha256 = "DCA9BCD395DEFFCA77C1D3919B4CC998234025059A892B10C3674C9A37D6DC9F";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.1.3/scala3-interfaces-3.1.3.pom";
      sha256 = "AE85E7A59BC5987AFAED043203616E87B37A68D4001DB9D3A4FE895AD4F057A1";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-javadoc.jar";
      sha256 = "2691EF1145EC68EAA0C9ED004C5A1E928443EC2E7867FC0A583348956C8A994F";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0-sources.jar";
      sha256 = "227C194B6AE5D38F4B3E10567279F5CC66AD49EE713081F4CE258998509D1166";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar";
      sha256 = "1AF055A657BEBD47D82E8825BB58A9C7602BEE0E6F041DDF38A177E9FDB5626B";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom";
      sha256 = "A7A6831F32F0662C449AABE7DC9B98BF653BAF311FAB2020E565CA5D73E9BB94";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3-javadoc.jar";
      sha256 = "E66D948B4773CEF0F3384D19E78369AC2D268A8D754C928E2954D5FD26E25298";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3-sources.jar";
      sha256 = "5E0639672DA01681B117781B6325374D3A3DD3D6BB12DE7782DC6C7B2115485D";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.jar";
      sha256 = "1AC79970D94A1762CE6AF4208820B4FA4C70093409DECAAD85C69D8B5F46E422";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.pom";
      sha256 = "D61E035994E678729D9EF1DCFE538BFE1E4A94E665DBD961A0FA327411A2F4D3";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3-sources.jar";
      sha256 = "1928C4FD961C46FE33B5DEDDDBD9B247E98E1AE055C4E038E4A944D8F8EBE433";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3.jar";
      sha256 = "28C563AD6049F51212C00A83878E6EAEE7EED8AAE28D74A00EC7AB489AEBB94B";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.1.3/scala3-sbt-bridge-3.1.3.pom";
      sha256 = "0580FC38E631AB0A88CAA9230A547F12616E335AC73D5E16988FA71A449C5A0B";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3-javadoc.jar";
      sha256 = "83BD3E33CF569606BA659F81706A8661F37A00778DCEA07516C7CDCA4D535D28";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3-sources.jar";
      sha256 = "1964AD7F177418B71592FF733A0D523DF5E3EA819EA6507D6C255C4E5B4F51D7";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3.jar";
      sha256 = "B9C6E3C196CB0EA15CFF650C8FD430A81BFB149336443921B3BCBDCB50243138";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.1.3/scala3-tasty-inspector_3-3.1.3.pom";
      sha256 = "F2FAD3DF82F292E3D006F8BAD620A701FCCD18B27CEE3B53212007E531110EAE";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3-javadoc.jar";
      sha256 = "AC947EDE6AEF6BDB669BA31F76BB1948F0BA1839D48929536DA8487FAC67E015";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3-sources.jar";
      sha256 = "E23495CFE93EC4444739539006B121AC18909A45EF45D2B370A2E29D40E259F5";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3.jar";
      sha256 = "1AAC8424BF8DDE5B298364B77BB497D9BF8A4F455AE46ABA95327AEA92C4C825";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.1.3/scaladoc_3-3.1.3.pom";
      sha256 = "55C4C96536C201285A00190B5FD7E74E997CD74D561FF6C9ED8ACF0255F2BC18";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3-sources.jar";
      sha256 = "18D84FC1FAA6B7D20EC480881F709332BDC17F9CBCB544A3B39723F62AC5FF7A";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3.jar";
      sha256 = "0A183E880575BCC97A2047761880241784734E7EE094DC6FAFD6A8F2109FF1DA";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.1.3/tasty-core_3-3.1.3.pom";
      sha256 = "7C59C26D8DFD507C75BE21A1D270FD68EC866C3895DB18996426BBC771597096";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5-javadoc.jar";
      sha256 = "523A46C23478661A50F4B3D29E2C1CA7B5272DF5D5E557ADEC08552DB7717D37";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5-sources.jar";
      sha256 = "302969948ADEBC53BE4BE5D73E088645D7CAFBABF5141C6504210B476DC57C93";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.jar";
      sha256 = "DF5D1931595B670769E98285CBDAC71C849F37A1573D4C1ACDAC4D2BD64CD689";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.3.5/compiler-interface-1.3.5.pom";
      sha256 = "FDCC0A98BB4A1A09B0780692F3FCA431B05F6146553DF3E85742E90D94988948";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar";
      sha256 = "A63861B771C20DF0DAB78F26A4FDD573C065FC569DDEF9C907A427B2F57C98A5";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar";
      sha256 = "C314491C9DF4F0BD9DD125EF1D51228D70BD466EE57848DF1CD1B96AEA18A5AD";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "15F70B38BB95F3002FEC9AEA54030F19BB4ECFBAD64C67424B5E5FEA09CD749E";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0-javadoc.jar";
      sha256 = "F8C0222BF1644FC12324A6A41175FCE02F854DB02F9D09322B685A146F01F0B1";
    };
    "nix-public/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0-sources.jar";
      sha256 = "469B23BDE6234973F9B0E8AFCF2E4EF0A7747F11000235F50038CAB1CBE0ED02";
    };
    "nix-public/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.jar";
      sha256 = "89028234B4621AC92761676A00E2E47598FCF5232A9BB994A7ED6DEE94EB5AA2";
    };
    "nix-public/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.3.0/util-interface-1.3.0.pom";
      sha256 = "984601D455B24A730455BD093DBD81ACA7A829FCF003DE3AB50309373EC3301E";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-javadoc.jar";
      sha256 = "F348AAA92D117701C628BE2ED7C5C04655A090765F02925DAB8B80CF227E9C52";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4-sources.jar";
      sha256 = "9C429B216222C4837C68F0FCD418D76453E6FE18D0D9393FC9D3E00CE0F7501F";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.jar";
      sha256 = "A344FC84EC8478B9FAF550116DF51E9FFF822448BFE279A05FEC8E16BFAB34E3";
    };
    "nix-public/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.15.4/scalacheck_3-1.15.4.pom";
      sha256 = "3DE696742D97B53A35BF5472DBFC1347D8C07E39B66207E1E8B4EF68E24F6678";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/yaml/snakeyaml/1.27/snakeyaml-1.27-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.27/snakeyaml-1.27-javadoc.jar";
      sha256 = "26301596A52A3C6529805933BDE96CD316889C9930E17D981BFD21B1CCA03256";
    };
    "nix-public/org/yaml/snakeyaml/1.27/snakeyaml-1.27-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.27/snakeyaml-1.27-sources.jar";
      sha256 = "04DEB12D97B76F715C14F8B5409F2111D01F21DBFE7A5ED5667E508785554AED";
    };
    "nix-public/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar";
      sha256 = "7E7CCE6740ED705BFDFAAC7B442C1375D2986D2F2935936A5BD40C14E18FD736";
    };
    "nix-public/org/yaml/snakeyaml/1.27/snakeyaml-1.27.pom" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.27/snakeyaml-1.27.pom";
      sha256 = "B495C4ED5A8D05513C1D881246DC50D5E15977C3CF6AAF9AD4283E06AC40477A";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-javadoc.jar";
      sha256 = "4574900538CCA041C62DEFE1A889E5DC8092C8118C554C7548ECAE344A1CB17C";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar";
      sha256 = "33A2CC43EEE1C2C1C3A57E68783B5B93CA05041C1505E67799DA43B0595E966C";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar";
      sha256 = "8EE3BE181A1D3871D2B14E1E145CBC48918ABBBF3596268FDD4B3D7292B07FC9";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom";
      sha256 = "DF50D06823A4F87C3FD739EBD1718F09BC126BB8206DFDE8C477B3A816EDF500";
    };
  };
}